//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.42
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePass.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap B15x13_KGPG_Gen {
            get {
                object obj = ResourceManager.GetObject("B15x13_KGPG_Gen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B15x14_FileNew {
            get {
                object obj = ResourceManager.GetObject("B15x14_FileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_1DownArrow {
            get {
                object obj = ResourceManager.GetObject("B16x16_1DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_1UpArrow {
            get {
                object obj = ResourceManager.GetObject("B16x16_1UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_2DownArrow {
            get {
                object obj = ResourceManager.GetObject("B16x16_2DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_2UpArrow {
            get {
                object obj = ResourceManager.GetObject("B16x16_2UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Apply {
            get {
                object obj = ResourceManager.GetObject("B16x16_Apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_ASCII {
            get {
                object obj = ResourceManager.GetObject("B16x16_ASCII", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Attach {
            get {
                object obj = ResourceManager.GetObject("B16x16_Attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Binary {
            get {
                object obj = ResourceManager.GetObject("B16x16_Binary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_BlockDevice {
            get {
                object obj = ResourceManager.GetObject("B16x16_BlockDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Browser {
            get {
                object obj = ResourceManager.GetObject("B16x16_Browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_CompFile {
            get {
                object obj = ResourceManager.GetObject("B16x16_CompFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Configure {
            get {
                object obj = ResourceManager.GetObject("B16x16_Configure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Cut {
            get {
                object obj = ResourceManager.GetObject("B16x16_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_DeleteEntry {
            get {
                object obj = ResourceManager.GetObject("B16x16_DeleteEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Edit {
            get {
                object obj = ResourceManager.GetObject("B16x16_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_EditCopy {
            get {
                object obj = ResourceManager.GetObject("B16x16_EditCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_EditDelete {
            get {
                object obj = ResourceManager.GetObject("B16x16_EditDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_EditPaste {
            get {
                object obj = ResourceManager.GetObject("B16x16_EditPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_EditShred {
            get {
                object obj = ResourceManager.GetObject("B16x16_EditShred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Error {
            get {
                object obj = ResourceManager.GetObject("B16x16_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Exit {
            get {
                object obj = ResourceManager.GetObject("B16x16_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_File_Locked {
            get {
                object obj = ResourceManager.GetObject("B16x16_File_Locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_FileNew {
            get {
                object obj = ResourceManager.GetObject("B16x16_FileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_FilePrint {
            get {
                object obj = ResourceManager.GetObject("B16x16_FilePrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_FileQuickPrint {
            get {
                object obj = ResourceManager.GetObject("B16x16_FileQuickPrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_FileSave {
            get {
                object obj = ResourceManager.GetObject("B16x16_FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_FileSave_Disabled {
            get {
                object obj = ResourceManager.GetObject("B16x16_FileSave_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_FileSaveAs {
            get {
                object obj = ResourceManager.GetObject("B16x16_FileSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Blue_Open {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Blue_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Home {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Inbox {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Inbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Locked {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Sent_Mail {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Sent_Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Txt {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Txt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Folder_Yellow_Open {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Yellow_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_FTP {
            get {
                object obj = ResourceManager.GetObject("B16x16_FTP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Help {
            get {
                object obj = ResourceManager.GetObject("B16x16_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_History {
            get {
                object obj = ResourceManager.GetObject("B16x16_History", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_History_Clear {
            get {
                object obj = ResourceManager.GetObject("B16x16_History_Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_HTML {
            get {
                object obj = ResourceManager.GetObject("B16x16_HTML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_HwInfo {
            get {
                object obj = ResourceManager.GetObject("B16x16_HwInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Identity {
            get {
                object obj = ResourceManager.GetObject("B16x16_Identity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_AmP {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_AmP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_AnyPw {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_AnyPw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_CWallet {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_CWallet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_PINs {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_PINs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_PVault {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_PVault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_PwAgent {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_PwAgent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_PwDepot {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_PwDepot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_PwGorilla {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_PwGorilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_PwSafe {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_PwSafe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Imp_Security {
            get {
                object obj = ResourceManager.GetObject("B16x16_Imp_Security", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KeePass {
            get {
                object obj = ResourceManager.GetObject("B16x16_KeePass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Keyboard_Layout {
            get {
                object obj = ResourceManager.GetObject("B16x16_Keyboard_Layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Gen {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Gen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Import {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Info {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Key1 {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Key1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Key2 {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Key2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Key3 {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Key3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KGPG_Sign {
            get {
                object obj = ResourceManager.GetObject("B16x16_KGPG_Sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KOrganizer {
            get {
                object obj = ResourceManager.GetObject("B16x16_KOrganizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_KRec_Record {
            get {
                object obj = ResourceManager.GetObject("B16x16_KRec_Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Laptop_Charge {
            get {
                object obj = ResourceManager.GetObject("B16x16_Laptop_Charge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_LockWorkspace {
            get {
                object obj = ResourceManager.GetObject("B16x16_LockWorkspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Misc {
            get {
                object obj = ResourceManager.GetObject("B16x16_Misc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_No {
            get {
                object obj = ResourceManager.GetObject("B16x16_No", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Package_Development {
            get {
                object obj = ResourceManager.GetObject("B16x16_Package_Development", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Package_Settings {
            get {
                object obj = ResourceManager.GetObject("B16x16_Package_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Personal {
            get {
                object obj = ResourceManager.GetObject("B16x16_Personal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Reload_Page {
            get {
                object obj = ResourceManager.GetObject("B16x16_Reload_Page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Spreadsheet {
            get {
                object obj = ResourceManager.GetObject("B16x16_Spreadsheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Toggle_Log {
            get {
                object obj = ResourceManager.GetObject("B16x16_Toggle_Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Trashcan_Full {
            get {
                object obj = ResourceManager.GetObject("B16x16_Trashcan_Full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Undo {
            get {
                object obj = ResourceManager.GetObject("B16x16_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_View_Detailed {
            get {
                object obj = ResourceManager.GetObject("B16x16_View_Detailed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Window_2Horz1Vert {
            get {
                object obj = ResourceManager.GetObject("B16x16_Window_2Horz1Vert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Window_3Horz {
            get {
                object obj = ResourceManager.GetObject("B16x16_Window_3Horz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_Wizard {
            get {
                object obj = ResourceManager.GetObject("B16x16_Wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_WWW {
            get {
                object obj = ResourceManager.GetObject("B16x16_WWW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B16x16_XMag {
            get {
                object obj = ResourceManager.GetObject("B16x16_XMag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B17x05_3BlackDots {
            get {
                object obj = ResourceManager.GetObject("B17x05_3BlackDots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B284x231_Random {
            get {
                object obj = ResourceManager.GetObject("B284x231_Random", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B32x32_Trashcan_Full {
            get {
                object obj = ResourceManager.GetObject("B32x32_Trashcan_Full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Ark {
            get {
                object obj = ResourceManager.GetObject("B48x48_Ark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Binary {
            get {
                object obj = ResourceManager.GetObject("B48x48_Binary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_BlockDevice {
            get {
                object obj = ResourceManager.GetObject("B48x48_BlockDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_FilePrint {
            get {
                object obj = ResourceManager.GetObject("B48x48_FilePrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Folder_Download {
            get {
                object obj = ResourceManager.GetObject("B48x48_Folder_Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Folder_Txt {
            get {
                object obj = ResourceManager.GetObject("B48x48_Folder_Txt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Font {
            get {
                object obj = ResourceManager.GetObject("B48x48_Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_KCMSystem {
            get {
                object obj = ResourceManager.GetObject("B48x48_KCMSystem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Keyboard_Layout {
            get {
                object obj = ResourceManager.GetObject("B48x48_Keyboard_Layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_KGPG_Gen {
            get {
                object obj = ResourceManager.GetObject("B48x48_KGPG_Gen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_KGPG_Key2 {
            get {
                object obj = ResourceManager.GetObject("B48x48_KGPG_Key2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_KGPG_Sign {
            get {
                object obj = ResourceManager.GetObject("B48x48_KGPG_Sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_KMag {
            get {
                object obj = ResourceManager.GetObject("B48x48_KMag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_KOrganizer {
            get {
                object obj = ResourceManager.GetObject("B48x48_KOrganizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_MessageBox_Info {
            get {
                object obj = ResourceManager.GetObject("B48x48_MessageBox_Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Package_Settings {
            get {
                object obj = ResourceManager.GetObject("B48x48_Package_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Run {
            get {
                object obj = ResourceManager.GetObject("B48x48_Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Source_Moc {
            get {
                object obj = ResourceManager.GetObject("B48x48_Source_Moc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_Wizard {
            get {
                object obj = ResourceManager.GetObject("B48x48_Wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_WWW {
            get {
                object obj = ResourceManager.GetObject("B48x48_WWW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B48x48_XMag {
            get {
                object obj = ResourceManager.GetObject("B48x48_XMag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon KeePass {
            get {
                object obj = ResourceManager.GetObject("KeePass", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon QuadLocked {
            get {
                object obj = ResourceManager.GetObject("QuadLocked", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon QuadNormal {
            get {
                object obj = ResourceManager.GetObject("QuadNormal", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
